# reference : https://www.cloudsavvyit.com/9490/how-to-dockerise-a-react-app
# docker build -t my-react-app:latest .
# docker run -d -p 8080:80 my-react-app:latest
FROM node:latest AS build
WORKDIR /build

COPY package.json package.json
COPY package-lock.json package-lock.json
RUN npm ci

COPY public/ public
COPY src/ src
RUN npm run build

FROM httpd:alpine
WORKDIR /var/www/html
COPY --from=build /build/build/ .